### ISSUE TITLE
aiohttp.client_exceptions.ServerDisconnectedError

### ISSUE THREAD

**Issue by gakelly** [thewhiteh4t/nexfil#30]
## Server Disconnected Error

While querying any username the script appears to run through many of the urls and then suddenly throws an exception.
I am not sure if this exception is caused by a bug in the code, my python version or a specific url but the error happens consistently.

Python version: `python 3.10.8`

```
Traceback (most recent call last):
  File "/home/gerard/osint/nexfil/nexfil.py", line 298, in <module>
    asyncio.run(main(uname))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/gerard/osint/nexfil/nexfil.py", line 281, in main
    await asyncio.gather(*tasks)
  File "/home/gerard/osint/nexfil/nexfil.py", line 181, in query
    response = await session.head(url, allow_redirects=True)
  File "/home/gerard/.local/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/gerard/.local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/gerard/.local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```
![WindowsTerminal_uDYS4kgMvf](https://user-images.githubusercontent.com/2339111/208224856-461ecb61-059b-4771-9d14-bde0bdffa4f2.gif)

**Comment by thewhiteh4t** [comment]
@gakelly thanks for reporting, I tested and I was able to reproduce the same error, looking into it now

**Comment by WeldFire** [comment]
Here's a PR to at least continue with the queries that work.
https://github.com/thewhiteh4t/nexfil/pull/32

Please let me know if you would like me to change this in any way @thewhiteh4t !

**Comment by thewhiteh4t** [comment]
@gakelly this exception has been handled in new version.
@WeldFire oops! thanks a lot for the PR I saw it too late

**Comment by gakelly** [comment]
> @gakelly this exception has been handled in new version. @WeldFire oops! thanks a lot for the PR I saw it too late

Excellent, I have confirmed that it is working as expected with the new version.
![image](https://user-images.githubusercontent.com/2339111/208351816-73c86516-93fa-4b94-a53a-18ea887b7935.png)
