### ISSUE TITLE
Error on Python 3.9 and 3.10

### ISSUE THREAD

**Issue by kaoxkrul** [thewhiteh4t/nexfil#36]
I'm having this issue on Arch Linux. Tested with python-3.9 and 3.10. Same error each time.

Traceback (most recent call last):
  File "/home/rk/nexfil/nexfil.py", line 298, in <module>
    asyncio.run(main(uname))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/rk/nexfil/nexfil.py", line 281, in main
    await asyncio.gather(*tasks)
  File "/home/rk/nexfil/nexfil.py", line 181, in query
    response = await session.head(url, allow_redirects=True)
  File "/home/rk/.local/lib/python3.9/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/rk/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/home/rk/.local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

**Comment by thewhiteh4t** [comment]
@kaoxkrul update to latest version

**Comment by Jaydepps** [comment]
same issue on version 3.11.1 (newest stable)

**Comment by thewhiteh4t** [comment]
@Jaydepps update nexfil to latest version
