### ISSUE TITLE
TypeError: function() argument 'code' must be code, not str

### ISSUE THREAD

**Issue by Jarvis4444** [thewhiteh4t/nexfil#43]
Hi,

Tried to running nexfil and get this error:
```
└─$ python3 nexfil.py -u username                                                                                                                  1 ⨯
[+] Importing Modules...
Traceback (most recent call last):
  File "/home/jarvis4444/Tools/nexfil/nexfil.py", line 112, in <module>
    import aiohttp
  File "/usr/lib/python3/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3/dist-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3/dist-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/usr/lib/python3/dist-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

Nexfil does work when not passing a username:
```
└─$ python3 nexfil.py -u                                                                                                                           1 ⨯
usage: nexfil.py [-h] [-u U] [-f F] [-l L] [-t T] [-v] [-U] [-pm PM] [-proto PROTO] [-ph PH] [-pp PP]
nexfil.py: error: argument -u: expected one argument
```

Uninstalled and reinstalled at version 1.0.3 so not sure if this is the UpToDate version or if this is a known problem

**Comment by Jarvis4444** [comment]
This seems to be a bigger issue with Harvester on my Kali machine not working with the same TypeError

**Comment by thewhiteh4t** [comment]
@Jarvis4444 it looks like your `aiohttp` is outdated, try `pip3 install --upgrade aiohttp`
