### ISSUE TITLE
Traceback error on pip install nexfil

### ISSUE THREAD

**Issue by HelloSecurityDev** [thewhiteh4t/nexfil#50]
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\REDACTED\AppData\Local\Temp\pip-install-m19pn9ac\undetected-chromedriver_7a7bb7151e0a4bc78dbb57243694f9ba\setup.py", line 52, in <module>
          long_description=open(os.path.join(dirname, "README.md")).read(),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1002: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Kellerossel** [comment]
This error originates from Unicode not being able to decode a certain character inside the readme.md if something in your chrome driver I believe. Try to open the readme file and maybe use another encoding
